apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemlistingwebapidepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListingWebApi
  template:
    metadata:
      labels:
        app: MenuItemListingWebApi
    spec:
      containers:
      - name: dockersamplerepos1
        image: menuitemcr.azurecr.io/dockersamplerepos1:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn1

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingwebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListingWebApi
